[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 200
headless = true
runOnSave = false
port = 8501

[browser]
gatherUsageStats = false

[logger]
level = "error"
messageFormat = "%(message)s"

[global]
developmentMode = false