[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 200
enableXsrfProtection = false
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
showErrorDetails = false

[client]
showErrorDetails = false

[logger]
level = "error"