[theme]
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
maxUploadSize = 200
enableXsrfProtection = false
headless = true
runOnSave = false
enableStaticServing = false

[browser]
gatherUsageStats = false
showErrorDetails = false
serverAddress = "0.0.0.0"

[client]
showErrorDetails = false
displayEnabled = false
toolbarMode = "minimal"

[logger]
level = "error"
messageFormat = "%(message)s"

[global]
developmentMode = false
showWarningOnDirectExecution = false