# Bu dosya Streamlit Cloud'da secrets olarak yüklenecek
# Gerekirse burada API anahtarları vb. tanımlanabilir

# Örnek:
# api_key = "your-api-key"
# database_url = "your-database-url"

# Şu an için boş - hiçbir secret yok